services:
  flowastudy.webapi:
    container_name: flowastudy
    image: ${DOCKER_REGISTRY-}flowastudywebapi
    build:
      context: .
      dockerfile: src/FlowaStudy.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - flowastudy.database
      - flowastudy.nosql
      - flowastudy.cache

  flowastudy.database:
    container_name: flowastudy_database
    image: postgres:13
    environment:
      POSTGRES_DB: flowastudy
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: teste123
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app_network
  flowastudy.nosql:
    container_name: flowastudy_nosql 
    image: mongo:8.0    
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: teste123
    ports:
      - "27017:27017"
    networks:
      - app_network

  flowastudy.cache:
    container_name: flowastudy_cache 
    image: redis:7.4.1-alpine     
    command: redis-server --requirepass teste123
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
